//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mms_project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mms_project()
        {
            this.mms_buildPart = new HashSet<mms_buildPart>();
        }
    
        public string ProjectCode { get; set; }
        public string ParentCode { get; set; }
        public string ProjectName { get; set; }
        public string ShortName { get; set; }
        public string OwnerUnit { get; set; }
        public string DesignUnit { get; set; }
        public string ConstructionUnit { get; set; }
        public string SupervisionUnit { get; set; }
        public string ChargePerson { get; set; }
        public Nullable<decimal> ContractMoney { get; set; }
        public Nullable<System.DateTime> ContractBeginDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> ActualBeginDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public Nullable<decimal> ActualDuration { get; set; }
        public string KeyProject { get; set; }
        public string FundSource { get; set; }
        public string Region { get; set; }
        public string ProjectArea { get; set; }
        public string BuildingType { get; set; }
        public string ProjectExplain { get; set; }
        public Nullable<decimal> BuildingArea { get; set; }
        public Nullable<decimal> CompleteArea { get; set; }
        public Nullable<decimal> ProjectCost { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mms_buildPart> mms_buildPart { get; set; }
    }
}
