//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mms_receive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mms_receive()
        {
            this.mms_receiveDetail = new HashSet<mms_receiveDetail>();
        }
    
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string DoPerson { get; set; }
        public string ProjectCode { get; set; }
        public string SupplierCode { get; set; }
        public string ContractCode { get; set; }
        public string WarehouseCode { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string MaterialType { get; set; }
        public string SupplyType { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string PayKind { get; set; }
        public string OriginalNum { get; set; }
        public string ApproveState { get; set; }
        public string ApprovePerson { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveRemark { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remark { get; set; }
    
        [Newtonsoft.Json.JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mms_receiveDetail> mms_receiveDetail { get; set; }
    }
}
