//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mms_productTest
    {
        public string ID { get; set; }
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public string ProductColor { get; set; }
        public string ProductType { get; set; }
        public Nullable<System.DateTime> ProductDate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Money { get; set; }
    }
}
