//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mms_merchants
    {
        public string MerchantsCode { get; set; }
        public string MerchantsName { get; set; }
        public string MerchantsTypeCode { get; set; }
        public string MerchantsTypeName { get; set; }
        public string ChargePerson { get; set; }
        public string ChargeTel { get; set; }
        public string RegisterFund { get; set; }
        public Nullable<System.DateTime> BuildDate { get; set; }
        public string BusinessScope { get; set; }
        public string BusinessType { get; set; }
        public string QualificationLevel { get; set; }
        public string Bank { get; set; }
        public string BankNo { get; set; }
        public string ContactPerson { get; set; }
        public string ContactTel { get; set; }
        public string ContactPosition { get; set; }
        public string ContactAddr { get; set; }
        public string ContactPostCode { get; set; }
        public string ContactFax { get; set; }
        public string Website { get; set; }
        public string EMail { get; set; }
        public string MajorSupplier { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Remark { get; set; }
    }
}
