//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MmsContext : DbContext
    {
        public MmsContext()
            : base("name=MmsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mms_buildPart> mms_buildPart { get; set; }
        public virtual DbSet<mms_check> mms_check { get; set; }
        public virtual DbSet<mms_checkDetail> mms_checkDetail { get; set; }
        public virtual DbSet<mms_deal> mms_deal { get; set; }
        public virtual DbSet<mms_dealDetail> mms_dealDetail { get; set; }
        public virtual DbSet<mms_direct> mms_direct { get; set; }
        public virtual DbSet<mms_directDetail> mms_directDetail { get; set; }
        public virtual DbSet<mms_lossReport> mms_lossReport { get; set; }
        public virtual DbSet<mms_lossReportBatches> mms_lossReportBatches { get; set; }
        public virtual DbSet<mms_lossReportDetail> mms_lossReportDetail { get; set; }
        public virtual DbSet<mms_material> mms_material { get; set; }
        public virtual DbSet<mms_materialType> mms_materialType { get; set; }
        public virtual DbSet<mms_materialWarnning> mms_materialWarnning { get; set; }
        public virtual DbSet<mms_merchants> mms_merchants { get; set; }
        public virtual DbSet<mms_merchantsType> mms_merchantsType { get; set; }
        public virtual DbSet<mms_productTest> mms_productTest { get; set; }
        public virtual DbSet<mms_project> mms_project { get; set; }
        public virtual DbSet<mms_receive> mms_receive { get; set; }
        public virtual DbSet<mms_receiveDetail> mms_receiveDetail { get; set; }
        public virtual DbSet<mms_refund> mms_refund { get; set; }
        public virtual DbSet<mms_refundDetail> mms_refundDetail { get; set; }
        public virtual DbSet<mms_rentIn> mms_rentIn { get; set; }
        public virtual DbSet<mms_rentInDetail> mms_rentInDetail { get; set; }
        public virtual DbSet<mms_rentOff> mms_rentOff { get; set; }
        public virtual DbSet<mms_rentOffDetail> mms_rentOffDetail { get; set; }
        public virtual DbSet<mms_rentOut> mms_rentOut { get; set; }
        public virtual DbSet<mms_rentOutDetail> mms_rentOutDetail { get; set; }
        public virtual DbSet<mms_rentOutRepaire> mms_rentOutRepaire { get; set; }
        public virtual DbSet<mms_rentOutReparation> mms_rentOutReparation { get; set; }
        public virtual DbSet<mms_repair> mms_repair { get; set; }
        public virtual DbSet<mms_repairDetail> mms_repairDetail { get; set; }
        public virtual DbSet<mms_return> mms_return { get; set; }
        public virtual DbSet<mms_returnBatches> mms_returnBatches { get; set; }
        public virtual DbSet<mms_returnDetail> mms_returnDetail { get; set; }
        public virtual DbSet<mms_send> mms_send { get; set; }
        public virtual DbSet<mms_sendBatches> mms_sendBatches { get; set; }
        public virtual DbSet<mms_sendDetail> mms_sendDetail { get; set; }
        public virtual DbSet<mms_stockAdjust> mms_stockAdjust { get; set; }
        public virtual DbSet<mms_stockAdjustDetail> mms_stockAdjustDetail { get; set; }
        public virtual DbSet<mms_transfer> mms_transfer { get; set; }
        public virtual DbSet<mms_transferBatches> mms_transferBatches { get; set; }
        public virtual DbSet<mms_transferDetail> mms_transferDetail { get; set; }
        public virtual DbSet<mms_warehouse> mms_warehouse { get; set; }
        public virtual DbSet<mms_warehouseStock> mms_warehouseStock { get; set; }
        public virtual DbSet<REMP_Change> REMP_Change { get; set; }
        public virtual DbSet<REMP_Department> REMP_Department { get; set; }
        public virtual DbSet<REMP_Staff> REMP_Staff { get; set; }
        public virtual DbSet<test_liy> test_liy { get; set; }
        public virtual DbSet<test_user> test_user { get; set; }
        public virtual DbSet<mms_test> mms_test { get; set; }
        public virtual DbSet<mms_warehouseStockHistory> mms_warehouseStockHistory { get; set; }
    }
}
