//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMP_Change
    {
        public int CHANID { get; set; }
        public Nullable<int> EMPSID { get; set; }
        public Nullable<System.DateTime> changedate { get; set; }
        public Nullable<int> changetype { get; set; }
        public Nullable<int> createtime { get; set; }
    
        public virtual REMP_Staff REMP_Staff { get; set; }
    }
}
