//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fruit.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMP_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REMP_Staff()
        {
            this.REMP_Change = new HashSet<REMP_Change>();
        }
    
        public int EMPSID { get; set; }
        public Nullable<int> DEPTID { get; set; }
        public string UserName { get; set; }
        public string EmployeeName { get; set; }
        public string DisplayName { get; set; }
        public string RealNameSpell { get; set; }
        public Nullable<int> UserType { get; set; }
        public string EmployeeCode { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Nationality { get; set; }
        public string Folk { get; set; }
        public string Native { get; set; }
        public string VoucherName { get; set; }
        public string UserIndentity { get; set; }
        public string Register { get; set; }
        public string OfficeAddress { get; set; }
        public string HomeAddress { get; set; }
        public string HomeZipCode { get; set; }
        public string OfficeFax { get; set; }
        public Nullable<int> IsStaff { get; set; }
        public Nullable<System.DateTime> InDutyDate { get; set; }
        public string TryDutyEndDate { get; set; }
        public string Duty { get; set; }
        public string OutDuty { get; set; }
        public string DutyLevel { get; set; }
        public string Polity { get; set; }
        public string Marry { get; set; }
        public string Diploma { get; set; }
        public string College { get; set; }
        public Nullable<System.DateTime> Graduationtime { get; set; }
        public string Major { get; set; }
        public string ProfessionalTitle { get; set; }
        public string ProfessionalTitleNo { get; set; }
        public string ProfessionalTime { get; set; }
        public string WorkCategory { get; set; }
        public string UserWeight { get; set; }
        public string UserHeight { get; set; }
        public string UserLike { get; set; }
        public string Special { get; set; }
        public Nullable<System.DateTime> SistartDate { get; set; }
        public string SocialInsurance { get; set; }
        public Nullable<int> IsPerformance { get; set; }
        public string TalkMan { get; set; }
        public string ParentMan { get; set; }
        public string PointMan { get; set; }
        public string CarNumber { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Mobile3 { get; set; }
        public string OICQ { get; set; }
        public string Email { get; set; }
        public string NetAddress { get; set; }
        public string SkypeUser { get; set; }
        public string EmergencyMan { get; set; }
        public string EmergencyRelation { get; set; }
        public string EmergencyPhone { get; set; }
        public string EmergencyMobile { get; set; }
        public Nullable<System.DateTime> SocialinsuranceOut { get; set; }
        public Nullable<System.DateTime> ConstarDate { get; set; }
        public Nullable<System.DateTime> ConendDate { get; set; }
        public Nullable<int> IsWagePay { get; set; }
        public string WageLevel { get; set; }
        public string WageCompany { get; set; }
        public string WagePassword { get; set; }
        public string WageAccounts { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> WorkgroupId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> DeletionStateCode { get; set; }
        public int Enabled { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public string ModifiedBy { get; set; }
        public string ApproveState { get; set; }
        public string ApprovePerson { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMP_Change> REMP_Change { get; set; }
        public virtual REMP_Department REMP_Department { get; set; }
    }
}
